#!/bin/bash

export REGISTRY="jenremote:5000"
export IMAGE=$(sed -n '1p' /tmp/.auth)
export TAG=$(sed -n '2p' /tmp/.auth)
#export PASS=$(sed -n '3p' /tmp/.auth)

#docker login -u user1 -p $PASS $REGISTRY
cd /home/jenkins/jenkins && docker-compose up -d
